%YAML 1.2
---
name: '7.Smyslov'                       # ideally no spaces
gpu: 0                                 # gpu id to process on

dataset: 
  num_chunks: 5                   # newest nof chunks to parse
  train_ratio: 0.80                  # trainingset ratio
  # For separated test and train data.
  input: '/content/gdrive/MyDrive/Project/TrainingData/7.Smyslov/' # supports glob
  # For a one-shot run with all data in one directory.
  # input: '/path/to/chunks/*/draw/'

training:
    batch_size: 256                   # training batch
    test_steps: 300                  # eval test set values after this many steps
    train_avg_report_steps: 100        # training reports its average values after this many steps.
    total_steps: 60               # terminate after these steps
    warmup_steps: 20                  # if global step is less than this, scale the current LR by ratio of global step to this value
    # checkpoint_steps: 10000          # optional frequency for checkpointing before finish
    shuffle_size: 300               # size of the shuffle buffer
   lr_values:                         # list of learning rates
        - 0.02
        - 0.002
        - 0.0002
    lr_boundaries:
          - 60000
          - 80000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    moves_left_loss_weight: .01        # weight of moves-left loss
    path: '/content/gdrive/MyDrive/Project/TrainedNetworks/'    # network storage dir

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 2                          # Squeeze Excite structural network architecture.
  policy: 'attention'                  # attention policy fields:
  pol_embedding_size: 64               # embedding vector size
  pol_encoder_layers: 1                # number of intermediate attention layers in the policy head
  pol_encoder_heads: 4                 # number of attention heads in encoder layers
  pol_encoder_d_model: 64              # size of the Q, K, & V vectors in encoder layers -- divisible by encoder_heads
  pol_encoder_dff: 128                 # size of the largest dense layer in encoder block feed-forward network
  policy_d_model: 64                   # size of the query and key vectors in final attention layer
  value: 'wdl'
  moves_left: 'v1'
...
